server:
  port: 8088
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/teenkiri
    username: root
    password: 1234

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      maxFileSize: 5120MB # 최대 5GB
      maxRequestSize: 5120MB # 최대 5GB


  # Email settings
  mail:
    host: smtp.gmail.com
    port: 587
    username: dldpsk122212@gmail.com
    password: vyqe nknv urcj rtyl
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true

  redis:
    host: localhost
    port: 6379
    #password: 1234

jwt:
  secret: secret_key
  expiration: 86400000  # 1 day in milliseconds

logging:
  level:
    root: INFO
    com.beyond.teenkiri: DEBUG
  file:
    name: application.log

# aws s3 설정
cloud:
  aws:
    credentials:
      access-key: YOUR_ACCESS_KEY_HERE       # 여기에 AWS 액세스 키를 입력하세요
      secret-key: YOUR_SECRET_KEY_HERE       # 여기에 AWS 시크릿 키를 입력하세요
    region:
      static: YOUR_REGION_HERE               # 여기에 AWS 리전을 입력하세요 (예: us-west-2)
    s3:
      bucket: YOUR_BUCKET_NAME_HERE          # 여기에 S3 버킷 이름을 입력하세요
